### ISSUE TITLE
atom安装失败

### ISSUE THREAD

**Issue by ChangeLeon** [apicloudcom/atom-apicloud-package#11]
atom：v1.16.0 x64

Installing “apicloud@0.2.0” failed.Hide output…
(node:17029) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.7.3 | linux | x64
gyp http GET https://atom.io/download/electron/v1.4.15/iojs-v1.4.15.tar.gz
gyp http 200 https://atom.io/download/electron/v1.4.15/iojs-v1.4.15.tar.gz
gyp http GET https://atom.io/download/electron/v1.4.15/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.226.200:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1033:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1056:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
gyp ERR! System Linux 4.9.24-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.4.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /home/leon/.atom
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

**Comment by ios122** [comment]
这个是 超时了. 说明连接 Atom 的插件托管的服务器,有问题. 可以尝试挂个 VPN 解决.或者从 源码安装.

1. 下载源码某个版本的 https://github.com/apicloudcom/atom-apicloud-package/releases

2. 源码解压放到 ~/.atom/packages 目录

3.在 ~/.atom/packages/atom-apicloud-package 目录执行,执行 ```npm i``` ,然后重启 Atom 即可

**Comment by ChangeLeon** [comment]
感谢，解决了
