### ISSUE TITLE
wifi真机同步,一直自动在同步,能不能关掉?

### ISSUE THREAD

**Issue by encircles** [apicloudcom/atom-apicloud-package#12]
wifi真机同步,一直自动在同步,能不能关掉?

**Comment by ios122** [comment]
周五,我们会发个增量更新,允许开发者自己定义是否自动同步.
目前,您可以采取临时方案关闭.如: 右键某个 html 文件 --> 实时预览 ,如此即可关闭WIFI 的自动同步

**Comment by APICloud-com** [comment]
老版还是新版的


yunying@apicloud.com
 
发件人： encircles
发送时间： 2017-06-08 17:30
收件人： apicloudcom/atom-apicloud-package
抄送： Subscribed
主题： [apicloudcom/atom-apicloud-package] wifi真机同步,一直自动在同步,能不能关掉? (#12)
wifi真机同步,一直自动在同步,能不能关掉?

**Comment by encircles** [comment]
studio2   @APICloud-com

**Comment by encircles** [comment]
@ios122  好的  我就是没找到   谢谢   辛苦了  你们都

**Comment by linuxliker** [comment]
wifi真机自动同步怎么开启？在webstorm中怎么开启？
