### ISSUE TITLE
atom ，同步问题

### ISSUE THREAD

**Issue by godmarvin** [apicloudcom/atom-apicloud-package#13]
怎么会自动进行wifi同步运行，快捷键屏蔽了都不行。

**Comment by ios122** [comment]
如果想关闭,在 偏好设置 --> apicloud --> 自动刷新 里

**Comment by godmarvin** [comment]
谢谢，已经找到了，你们工具的自动刷新功能，是不是应该默认关闭着呀，不然我还以为是工具出问题了呢？
